[[section-design-decisions]]
== Design Decisions


The key of this project is the decentralization of data.

For working with data decentralization we will be using Solid, a project by Prof. Tim Berners-Lee, as is one of the
prerequisites of this project, has and intuitive form of use and works very well with different programming languages
and especially with the one we will be using: JavaScript, as it was created with it.

JavaScript was also chosen because it counts with different libraries, as LDFlex for example, that makes working with
solid a lot easier; it is also a high demanded and used language and it gives us the opportunity to learn more about it
and in case this projects ends up becoming free source in this language it will probably be more useful for the
rest of the community.

Using solid and JavaScript will make achieving quality goals easier. Solid will provide security and privacy regarding
the data while JavaScript counts with different libraries for correct and safe connections between the pods and the
client.
We will also implement more security at the client manually and with other JS libraries specialized on it.

Quality will also be increased as we will work with high ranking technologies that we are used to as all the time we
would expend documenting this development environment we will use it improving other factors of our project.We are
going to use WebStorm for coding and editing our documentation as it is an IDE that provides both funcionalities and
most of us are used to it. Also we are going to use github as version control manager as is the one used in our
university and one of the leader platforms to share free source code.

Regarding design we will be using the MVC pattern. Solid provides by itself a modular design form by different pods
containing the client data, and we want to keep the decentralization of that data as clear as possible so by structuring
the project with this pattern we will have the exact responsibilities of each layer and the way they communicate to
each other very clear.

To achieve all this we will be following a agile methodology. All of us will have the software architect role so at
the meetings all of us will have to take that role and manage to share it with the rest of the group, we will split
the task in the smallest possible and keep developing,making documentation and communicating with the rest of the group
during all the process.
