[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree



=== Quality Scenarios

****
.Usage Scenarios:
* An user attempts to access the porfile of a friend -> the application makes a request to the server to access the porfile's contents of the friend's POD, retrieves them, and shows them to the user within 1 second (multimedia content may vary)
* An user attempts to access the porfile of a person that has explicitly set their profile to private -> the application makes a request to the server to access the porfile's contents of the person's POD, but due to the lack of permission the access is denied and the requesting user is informed within 1 second 
* An user changes his/her porfile picture -> The application request the server storing the POD to edit the contents, and upon obtainin permission he changes the picture. from now on people accessing this  porfile will see the updated picture
* An user wants to start a conversation with a friend -> The application makes a request to estabish a line of communication between the current device and the device in which the friend has his app installed within 2 seconds. 
* An user wants to start a conversation with an user he isn't friends with -> The application makes a request to estabish a line of communication between the current device and the device in which the user has his app installed. Due to them not being friends, the application will first make a request to the friend's POD to reveal the device in which the app is installed to establish communication: the user will first have to personally accept this request (unless stated otherwise in configuration) before the application is allowed to know the device he must communicate with. Both the user being contacted and the person trying to contact them will have the capacity to block and/or report the person they are communicating with at any moment.
 
.Change Scenarios:
* The application is modified to be integrated with Github -> the Application now can retrieve information from the linked GitHub account, informing the user with each relevant action (Commits, updates in repostories, requests to participate in projectts, etc). If Application friends link their accounts to the application and they allow that information to be shared in settings, the user will be informed that they share platform.

****
