language: node_js
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
  - npm install
  - npm install --save howler
  - npm audit fix
script:
  - ng build --prod
after_success:
  - bash <(curl -s https://codecov.io/bash)


