language: node_js
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
script: 
  - ng build --prod
  - npm run test -- --no-watch --no-progress
after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)


