language: node_js
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
script: 
  - ng build --prod
  - npm run test -- --no-watch --no-progress --browser=ChromeHeadlessCI
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run coverage

