language: node_js
node_js:
  - "10.15"
addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install
  - npm install --save howler
  - npm install solid-auth-client
  - npm install solid-file-client@0.4.9
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - ng build --prod
after_success:
  - node_modules\.bin\cucumber-js src\test\dechatCucumber\features -r src\test\dechatCucumber\features\step_definitions
  - bash <(curl -s https://codecov.io/bash)
