language: node_js
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
  - npm install
  - npm install --save howler
  - npm install solid-auth-client
  - npm install solid-file-client@0.4.9
  - ng test --watch=false --code-coverage
  - ng build --prod
after_success:
  - node_modules\.bin\cucumber-js src\test\dechatCucumber\features -r src\test\dechatCucumber\features\step_definitions
  - bash <(curl -s https://codecov.io/bash)
