[[section-solution-strategy]]
== Solution Strategy

The main and final decisions are further explained at the fourth
section of this document, Design decisions, but an index of these is:

[upperroman]
. Architecture and design decisions
[upperroman]
.. MVC by Angular
.. Modular Desing by Solid
. Programing languages
[upperroman]
.. Angular [TypeScript]
. Technologies
[upperroman]
.. WebStorm by Jetbrains
.. Github
. Methodologies
[upperroman]
.. Scrum
. Testing
[upperroman]
.. Cucumber
.. Karma and Jasmine

It is needed to mention that, during the investigation and first
development sprint, we took different alternatives of these technologies into account,
what it is more, Angular was itself one of these, as we starting our project with the idea
of using react but due to the lack of documentation and our knowledge of this tool
we decided that Angular would be a better choice.
We also used different tools for documentation before knowing we could use
WebStorm or VisualStudio and many others as Selenium instead of cucumber
or Mocha instead of Jasmine. After the first sprint of trying different tools, doing
tutorials and lots of investigation we end up choosing the technologies and software
indicated above.
